# .github/workflows/firebase-hosting-pull-request.yml

name: Validate Pull Request

on:
  pull_request:

jobs:
  build:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest

    steps:
      # Checkout the PR code
      - name: Checkout code
        uses: actions/checkout@v4

      # Install dependencies and verify the application builds
      - name: Install dependencies and build
        run: |
          npm ci
          npm run build
